### PR TITLE
Ensure block moves don't invalidate eligibility predicates

### LINKED ISSUE #3744: Tracking: Eligibility conditions for programs
Tracking issue for adding Eligibility checking to programs.

The basic approach will be to mimic the Show/Hide system and re-use the Predicate logic backend flows and data storage.

This does not include the feature flag being removed (that is tracked [here](https://github.com/civiform/civiform/issues/4605)).

[Design Doc](https://docs.google.com/document/d/1A7ftdnAOghd2BCohNRtppyRpB4oKkik_0zAal4yUcuk/edit#heading=h.fvf1dku1q5pk) 

## Predicate logic system
 
- [x] Support and/or operations #3743 
- [x] Storage for Eligibility Predicates #3922
- [x] Feature Flag #3923

## Admin Flows
- [x] -- Evaluate eligibility questions #3926
- [x] -- Add/Remove eligibility #3932 
- [x] -- Restrict Eligibility available questions to the block #4025 
- [x] -- Show eligibility in Application view #4079

## Applicant Flows 
- [x] -- Evaluate eligibility upon submit #4080
- [x] -- Cleanup IneligibleBlockView #4083
- [x] -- Show status in preview/review page #4002 
- [x] -- Show not eligible banner on pre-view page #4141
- [x] -- Show status on program list for in-progress application #4142

## Trusted Intermediary Flows 
- [x] -- Ensure correct text shows for trusted intermediaries #4184

## Custom logic
- [x] Fix Currency Predicates #3854

## Other
- [x] Add translations #4127
- [x] #4315

### PR DESCRIPTION
**Pull request by shanemc-goog**
### Description

When a block is moved or removed, verify that it doesn't invalidate eligibility predicates needing to access questions before or on its block.

## Release notes

The title of the pull request will be used as the default release notes description. If more detail is needed to communicate to partners the scope of the PR's changes, use this release notes section.

#### General

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [x] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

#### User visible changes

- [ ] Wrote browser tests using the [validateAccessibility](https://sourcegraph.com/github.com/civiform/civiform/-/blob/browser-test/src/support/index.ts?L437:14&subtree=true) method
- [ ] Manually tested at 200% size
- [ ] Manually evaluated tab order

#### New Features

- [ ] Add new FeatureFlag env vars to `server/conf/application.conf`
- [ ] Conditioned new functionality on a [FeatureFlag](https://docs.civiform.us/contributor-guide/developer-guide/feature-flags)
- [ ] Wrote browser tests with the feature flag off and on, etc.

### Issue(s) this completes

Fixes #3744

### CODE REVIEW

**Review by nbeloglazov — CHANGES_REQUESTED** [review]
Can you add unit or browser test for this new check?

**Comment by shanemc-goog** [comment]
> Can you add unit or browser test for this new check?

Good catch!!  The test got lost somehow and I didn't realize it.  Added!

**Review by nbeloglazov — APPROVED** [review]
Do we have similar check when a question that is used in predicate gets removed?

**Comment by shanemc-goog** [comment]
> Do we have similar check when a question that is used in predicate gets removed?

Ah yeah, when the block the predicates question is deleted.  Added that test too, those are the only (indirect) public callers of the method I updated.

**Review by nbeloglazov — APPROVED** [review]

**Pull request merged**
