### PR TITLE
Remove the uses fixtures tag since all tests use fixtures now

### PR DESCRIPTION
**Pull request by devin-civi**
### Description

Remove the uses fixtures tag because all tests use fixtures now. Also removes unused code related to creating a test context.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | under-development | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers)
- [x] Added an additional reviewer from outside your organization as FYI (if the primary reviewer is in the same

### CODE REVIEW

**Comment by devin-civi** [comment]
* **#7454** <a href="https://app.graphite.dev/github/pr/civiform/civiform/7454?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @devin-civi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by gwendolyngoetz — APPROVED** [review]
:partying_face:

**Comment by gwendolyngoetz** [comment]
This has been a long time coming since I started this in January. Thanks you for getting the rest of them done!!!!!!

**Review by jeffpw-goog — APPROVED** [review]
🥳🥳

**Pull request merged**
