### PR TITLE
Use two-digit hour in exports

### PR DESCRIPTION
**Pull request by nb1701**
This string not being a predictable length for every entry caused problems for Excel and Tableau to automatically read the data as timestamps. This changes it to always print a two-digit hour, prepending with a 0 as needed.

https://github.com/civiform/civiform/issues/6464

### CODE REVIEW

**Review by avaleske — APPROVED** [review]
Yet another thing I wish I had noticed when I started API stuff last summer. My "current status" audit was... not thorough.

It's _probably_ fine, but before merging we should:
- a) Test what happens when parsing two digit hour datetime with a single digit hour format, like `LocalDate.parse(text, "yyyy/MM/dd 'at' h:mm a z")`. If it works fine then there's less concern here.
- b) Let the civic entities know this change is coming and get their signoff, especially Arkansas. Matthew at Arkansas will be the one with the most knowledge of their API consuming code. (And if they're ok with it, changing it to an ISO date would be especially nice.)

Alternatively, we could add new time fields to the CSV and JSON API called `create_time_iso` and use an ISO format like we should've from the start, and eventually deprecate the current fields.

fwiw, the more formal process for changing an in-use API feature that I'm proposing is:
https://docs.google.com/document/d/1aKQ55fRdCxvYd9XMd2p9PJxQuSuEIPJoE9-O-pSjWsQ/edit#bookmark=id.qt2b8u6lfpgv

**Comment by isabelcshaw** [comment]
@nb1701 @avaleske Matthew confirmed that he's good with using an ISO format

**Comment by avaleske** [comment]
> @nb1701 @avaleske Matthew confirmed that he's good with using an ISO format

just said the same on the issue! https://github.com/civiform/civiform/issues/6464

**Review by avaleske — APPROVED** [review]
Thank you!

**Comment by avaleske** [comment]
Oh please also update the api docs:
- https://github.com/civiform/docs/blob/main/docs/it-manual/api/program-applications.md#create_time
- https://github.com/civiform/docs/blob/main/docs/it-manual/api/program-applications.md#submit_time

**Pull request merged**
