### PR TITLE
Add feature flag for multiple uploads

### PR DESCRIPTION
**Pull request by devin-civi**
### Description

Add feature flag for multiple uploads. This is for Issue #6961.

#### New Features

- [x] Add new FeatureFlag env vars to `server/conf/helper/feature-flags.conf`

### Instructions for manual testing

If instructions are needed for manual testing by reviewers, include them here.

### Issue(s) this completes

Fixes #<issue_number>; Fixes #<issue_number>...

### CODE REVIEW

**Comment by devin-civi** [comment]
* **#7495** <a href="https://app.graphite.dev/github/pr/civiform/civiform/7495?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @devin-civi and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by melanie-exygy — COMMENTED** [review]
This looks good to me, but I wonder if you should enable the flag in the dev config and disable it by default for browser tests.  The instructions in the wiki say to do that, but I've noticed that many flags are missing from those files.  I posed the question in [Slack](https://civiform.slack.com/archives/C01QKN2UNMA/p1717625453937459).  Let's see what people say.

**Review by melanie-exygy — APPROVED** [review]

**Comment by melanie-exygy** [comment]
> This looks good to me, but I wonder if you should enable the flag in the dev config and disable it by default for browser tests. The instructions in the wiki say to do that, but I've noticed that many flags are missing from those files. I posed the question in [Slack](https://civiform.slack.com/archives/C01QKN2UNMA/p1717625453937459). Let's see what people say.

Sounds like we don't need to add it to the dev and browser config files.  So, you're good to go!

**Comment by devin-civi** [comment]
Thanks for checking!

**Pull request merged**
