### PR TITLE
Adding sort on getAllProgramSlugs

### PR DESCRIPTION
**Pull request by gwendolyngoetz**
### Description

Sort the slugs in getAllProgramSlugs

#### General

Read the full guidelines for PRs [here](https://docs.civiform.us/contributor-guide/developer-guide/technical-contribution-guide#guidelines-for-pull-requests)

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release | database >
- [x] Performed manual testing (Chrome and Firefox if it includes front-end changes)

### CODE REVIEW

**Review by avaleske — APPROVED** [review]
Should the other `getAllProgramNames()` and related methods also be sorted?

**Comment by gwendolyngoetz** [comment]
I believe everything show to the user should have a sort on it. Poor UX to have to scour through a list. In this case the only other place using the `getAllProgramSlugs` method is in the api key generator and I checked and it looks better now too.

**Comment by avaleske** [comment]
> I believe everything shown to the user should have a sort on it. Poor UX to have to scour through a list. In this case the only other place using the `getAllProgramSlugs` method is in the api key generator and I checked and it looks better now too.

Ah sorry to clarify: I agree. I was asking if, while you're there, you thought `getAllProgramNames()` should also sort its output.

**Comment by gwendolyngoetz** [comment]
I think it should, but that feels like it has the potential for extra work beyond just adding the sort.

**Pull request merged**
