### PR TITLE
Add Install instructions, debugger ports, and fix formatter for browsertests

### PR DESCRIPTION
**Pull request by kmcnellis**
### Description

- Have the browsertest local script detect if you have node, and prompt for installation if you do not.
- Use npx to run yarn, so you don't need to manually install it.
- Use a prober-loop to wait to run local tests until the server is done compiling
- Fix the `browser-test/bin/fmt` formatting script (browsertest doesn't have it's own prettier config, so it needs to be built-in to the image)
- Update the vscode config to have debugging ports & recommended packages in the main civiform.code-workspace file

## Release notes:

n/a

### Checklist

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [ ] Created tests which fail without the change (if possible)
- [x] Extended the README / documentation, if necessary (https://github.com/civiform/docs/pull/105)

### Issue(s)

Helps with https://github.com/civiform/civiform/issues/3058

### CODE REVIEW

**Comment by shanemc-goog** [comment]
update the doc please "a little easier to run locally"  How? :)

Also check the boxes for release label/notes

**Comment by shanemc-goog** [comment]
Check the box please :D. "Added the correct label"

**Review by shanemc-goog — APPROVED** [review]

**Review by nbeloglazov — APPROVED** [review]
How does it fix formatter? Was it broken?

**Comment by kmcnellis** [comment]
> How does it fix formatter? Was it broken?

Yeah - it wasn't working from browser-test/bin/fmt

**Comment by nbeloglazov** [comment]
Curious, why do we have `browser-test/bin/fmt`? It is a subset of `bin/fmt` that allows to format only TS files?

**Review by nbeloglazov — APPROVED** [review]

**Pull request merged**
