### PR TITLE
Add feature flag for saving applicant data on Review button click or Previous button click.

### PR DESCRIPTION
**Pull request by caitlinshk**
### Description

To address https://github.com/civiform/civiform/issues/6450, we're going to update the Review and Previous buttons to save an applicant's answers when clicked. (Right now, their answers are just thrown away and applicants could lose a lot of work.) Because the fix will affect the core applicant journey, I'm going to guard it behind a feature flag so that we can do extensive testing before releasing it.

#### General

Read the full guidelines for PRs [here](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#creating-a-pull-request)

- [x] Added the correct label: < feature | enhancement | bug | dependencies | infrastructure | ignore-for-release | database >
- [x] Assigned to a specific person, `civiform/developers`, or a [more specific round-robin list](https://github.com/civiform/civiform/wiki/Technical-contribution-guide#adding-reviewers).

#### New Features

- [x] Add new FeatureFlag env vars to `server/conf/helper/feature-flags.conf`

### Issue(s) this completes

Needed for #6450

### CODE REVIEW

**Comment by caitlinshk** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #6529** <a href="https://app.graphite.dev/github/pr/civiform/civiform/6529?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/civiform/civiform/6529?utm_source=stack-comment).

**Comment by swatkat1** [comment]
Non-blocking - Will you be following with a PR to the CiviForm deploy repo?

**Comment by swatkat1** [comment]
Looks like there are some merge conflicts

**Comment by caitlinshk** [comment]
> Non-blocking - Will you be following with a PR to the CiviForm deploy repo?

Yes! I just figured this should be submitted first.

**Comment by caitlinshk** [comment]
> Looks like there are some merge conflicts

Addressed merge conflicts!

**Review by swatkat1 — APPROVED** [review]

**Pull request merged**
