### PR TITLE
Text changes on Ineligibility screen

### LINKED ISSUE #4246: Update text on eligibility screen
**Is your feature request related to a problem? Please describe.**
We would like to update the text on the eligiblity screen (the one that lets residents know they don't qualify)

**Describe the solution you'd like**
Text changes, below

image

### PR DESCRIPTION
**Pull request by swatkat1**
### Description
Text changes in Ineligibility Screen.

## Release notes

Text changes in Ineligibility Screen (gated by a feature flag).

#### General

- [x] Added the correct label: < feature | bug | dependencies | infrastructure | ignore-for-release >
- [x] Created tests which fail without the change (if possible)
### Issue(s) this completes

Fixes #4246

### CODE REVIEW

**Comment by dkatzz** [comment]
We'll need to get translations for the new strings - could you add them [here](https://docs.google.com/spreadsheets/d/1x9xq-X61Gev2c470dPYe69tzI4azLTerZu-jfzFHmTE/edit?resourcekey=0-6T7y1Mv3Rr_u1rkmhGCeuQ#gid=1850787383)?

**Comment by swatkat1** [comment]
image
I am unable to access the page. I had already requested access but haven't received.

@dkatzz  - It should be not be ignored for releas. Seattle has already turned on the feature in PROD. Also, if it ignored for release, Matt won't be able to test it in staging. Generally speaking, dependency changes are marked as 'ignore for release'.

**Comment by dkatzz** [comment]
> Text changes in Ineligibility Screen.

Sorry about the access issue - I can look into that but in the meantime I can add this translation.

Sounds good about the tag - would you mind just adding "(gated by a feature flag)" to the release notes section.

Thanks!

**Review by dkatzz — APPROVED** [review]

**Comment by swatkat1** [comment]
Thanks for adding the translation! I have updated the release notes.

**Comment by dkatzz** [comment]
> Thanks for adding the translation! I have updated the release notes.

Thank you!!

**Pull request merged**
